### PR TITLE
MiTemp MQTT demo

### PR DESCRIPTION
**Pull request by yolkhovyy**
The demo publishes MiTemp measurements on MQTT, usage:

python3 /path/to/mitemp_mqtt.py 58:2D:34:36:82:ED -m -e -s mqtt-server

E.g. cron, every 15 minutes:

*/15 * * * * python3 /path/to/mitemp_mqtt.py 58:2D:34:36:82:ED -m -e -s mqtt-server

### CODE REVIEW

**Comment by ratcashdev** [comment]
thanks will check it out.

**Comment by yolkhovyy** [comment]
I have removed the btlewrap and other unnecessary changes - please review, thanks!

**Comment by ratcashdev** [comment]
Hi @yolkhovyy, thanks for the update.
I have configured Github actions CI for this project. Please update this PR by merging master here. Afterwards fix the flak8 errors. I can see several of them. I don't see tests either for your changes.

**Comment by yolkhovyy** [comment]
I have merged the changes from the original. Will add an integrat

**Comment by yolkhovyy** [comment]
I have merged the original, will make an integration test for mitemp-mqtt.py

**Comment by ratcashdev** [comment]
@yolkhovyy You're indeed right. It's better to keep things modular. Anyway thank you for your efforts so far.

**Pull request closed without merging**
