### PR TITLE
add support for new thermometer

### PR DESCRIPTION
**Pull request by gallynero**
references #17 

allow read data fron new version of Xiaomi thermometer

For test can use demo.py with --version V2 argument, for example:

python3  demo.py --backend gatttool --version V2 poll <mac>

### CODE REVIEW

**Comment by yabolek** [comment]
Getting data from Mi Temperature and Humidity Sensor
FW: 1.0.0_0106
Name: LYWSD03MMC
Battery: 99
Temperature: 22.43
Humidity: 58.678

From the Xiaomi app:
temp 22,5 C
Humidity 55%

How can I update this code in Home Assistant?

**Comment by gallynero** [comment]
i will close this pull request, i found a bug in the humidity, i will repair and make one new.

**Comment by gallynero** [comment]
i fix the humidity value in the pull request #19, now is working ok.

If the autor not response i will adapt this to work with home assistant

**Comment by gallynero** [comment]
> Getting data from Mi Temperature and Humidity Sensor
> FW: 1.0.0_0106
> Name: LYWSD03MMC
> Battery: 99
> Temperature: 22.43
> Humidity: 58.678
> 
> From the Xiaomi app:
> temp 22,5 C
> Humidity 55%
> 
> How can I update this code in Home Assistant?

Hi,

i created a new integration for new themp sensor of xiaomi, can you download from https://github.com/gallynero/mitemp2_bt

**Pull request closed without merging**
