### PR TITLE
Fix for single digit values thank to @rmiddlet

### PR DESCRIPTION
**Pull request by f-bader**
Original thanks to @rmiddlet 
Fix for issue #2 and #4 

Tested on a raspberry pi

### CODE REVIEW

**Comment by sjol** [comment]
I can confirm this is working as my sensor is outside and it's winter.

**Comment by ratcashdev** [comment]
Thank you, will have a look.

**Comment by ratcashdev** [comment]
@f-bader thanks for the submission. Could you possibly add also tests for this change?

**Comment by f-bader** [comment]
Sure. Will take a look at the tests later today

**Comment by f-bader** [comment]
@ratcashdev Please check my changes to test_parse.py

**Comment by ratcashdev** [comment]
@f-bader tests are failing (run `tox`)
```
>           for dataitem in data.strip('\0').split(' '):
E           TypeError: a bytes-like object is required, not 'str'
```

**Comment by ratcashdev** [comment]
There are also some pylint errors.

**Comment by f-bader** [comment]
Hi @ratcashdev 

I tried to fix the tests but encounter an erro with python 2.7
This example code works fine with python 3.6 but not with 2.7

`MI_TEMPERATURE = "temperature"`
`MI_HUMIDITY = "humidity"`
`MI_BATTERY = "battery"`
``
`data = bytes([0x54, 0x3d, 0x32, 0x35, 0x2e, 0x36, 0x20, 0x48, 0x3d, 0x32, 0x33, 0x2e, 0x36, 0x00]).decode("utf-8").strip(' \n\t')`
``
`res = dict()`
`for dataitem in data.strip('\0').split(' '):`
`  dataparts = dataitem.split('=')`
`  if dataparts[0] == 'T':`
`    res[MI_TEMPERATURE] = float(dataparts[1])`
`  elif dataparts[0] == 'H':`
`    res[MI_HUMIDITY] = float(dataparts[1])`
`res`
`data.strip('\0').split(' ')`
Python 2.7.15rc1
> {}
> [u'[84,', u'61,', u'50,', u'53,', u'46,', u'54,', u'32,', u'72,', u'61,', u'50,', u'51,', u'46,', u'54,', u'0]']
Python 3.6.7
> {'temperature': 25.6, 'humidity': 23.6}
> ['T=25.6', 'H=23.6']

If i replace the test data with `data = str("T=25.6 H=23.6")` instead of the hex values it works just fine

Would that be fine for the unit tests as well?
Will commit these changes if you give green light.

**Comment by ratcashdev** [comment]
@f-bader It's important that we fill-in such data that are received from the device, actually, with the same type.  During real operation `handleNotification` is the method, that populsates the _cache field, and it is doing so using `self._cache = raw_data.decode("utf-8").strip(' \n\t')`
It would be nice if the tests could use the same sequence of processing instructions as handleNotification.  Thus I propose to do the tests like this: 
```
 def test_parsing(self):
        """Does the Mi TEMP BT data parser works correctly?"""
        poller = MiTempBtPoller(None, MockBackend)
        data = bytes([0x54, 0x3d, 0x32, 0x35, 0x2e, 0x36, 0x20,
                      0x48, 0x3d, 0x32, 0x33, 0x2e, 0x36, 0x00]).decode("utf-8").strip(' \n\t')
        poller._cache = data
        poller._last_read = datetime.now()
        self.assertEqual(poller._parse_data()[MI_TEMPERATURE], 25.6)
        self.assertEqual(poller._parse_data()[MI_HUMIDITY], 23.6)

```

**Comment by f-bader** [comment]
@ratcashdev I understand. But sadly this does not work with python 2.7 as described in my last post. So there seems to be a difference between the `rawdata` and the used `bytes`
I check if I can find a solution that work for both Python versions.

**Comment by ratcashdev** [comment]
@f-bader  Python 2.7 is not supposed to work. See test/unit_tests/test_versioncheck.py

**Comment by f-bader** [comment]
@ratcashdev Changed the code to use `bytearray` instead of `bytes` and how tox is fine with the tests
`bytes` is interpreted as `string` which result in the error

**Comment by ratcashdev** [comment]
Checked your latest commit. There are still some errors by tox.
`tox -e py27,py35,py36,flake8`

**Pull request merged**
